import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createNitro } from 'nitro/builder'
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest'
import mcp from '../src/module/index.ts'
import { fixtureDir, modules } from './helpers/discovery-fixture.ts'
import type { Nitro } from 'nitro/types'

/** Absolute paths are machine-specific; the shape of the module is not. */
function readable(code: string): string {
  return code.replaceAll(fixtureDir, '<fixture>')
}

async function render(nitro: Nitro, id: string): Promise<string> {
  const template = nitro.options.virtual[id]

  return readable(typeof template === 'function' ? await template() : (template ?? ''))
}

describe('the mcp() module', () => {
  let nitro: Nitro

  beforeAll(async () => {
    // Installs both instances against the fixture tree, without building it.
    nitro = await createNitro({ rootDir: fixtureDir, dev: false, preset: 'standard', modules })
  })

  afterAll(async () => {
    await nitro.close()
  })

  it('mounts each instance on its own route', () => {
    expect(nitro.options.handlers).toMatchObject([
      { route: '/mcp', handler: '#mcp/mcp/handler', lazy: true, middleware: false },
      { route: '/admin/mcp', handler: '#mcp/admin-mcp/handler', lazy: true, middleware: false },
    ])
  })

  it('generates a registry of everything it discovered', async () => {
    await expect(render(nitro, '#mcp/mcp/registry')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.

      import _0 from "<fixture>/server/mcp/tools/greet-visitor.ts"
      import _1 from "<fixture>/server/mcp/tools/named.ts"
      import _2 from "<fixture>/server/mcp/tools/nested/deep.ts"
      import _3 from "<fixture>/server/mcp/resources/readme.ts"
      import _4 from "<fixture>/server/mcp/prompts/review.ts"

      const fromFile = (definition, { name, title, ...source }) => ({
        ...definition,
        name: definition.name ?? name,
        title: definition.title ?? title,
        source,
      })

      export const tools = [
        fromFile(_0, {"name":"greet-visitor","title":"Greet Visitor","file":"tools/greet-visitor.ts"}),
        fromFile(_1, {"name":"named","title":"Named","file":"tools/named.ts"}),
        fromFile(_2, {"name":"deep","title":"Deep","file":"tools/nested/deep.ts","group":"nested"}),
      ]

      export const resources = [
        fromFile(_3, {"name":"readme","title":"Readme","file":"resources/readme.ts"}),
      ]

      export const prompts = [
        fromFile(_4, {"name":"review","title":"Review","file":"prompts/review.ts"}),
      ]
      "
    `)
  })

  it('serves each route from its own registry', async () => {
    await expect(render(nitro, '#mcp/admin-mcp/handler')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.
      import { createMcpHandler } from 'nitro-mcp-toolkit'
      import { prompts, resources, tools } from "#mcp/admin-mcp/registry"

      export default createMcpHandler({
        name: "admin-fixture",
        version: "1.0.0",
        tools,
        resources,
        prompts,
      })
      "
    `)
  })

  it('passes what the server advertises through to the handler', async () => {
    const iconic = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [
        mcp({
          route: '/iconic',
          icons: [{ src: 'https://example.com/icon.png', mimeType: 'image/png' }],
          websiteUrl: 'https://example.com',
        }),
      ],
    })

    const code = await render(iconic, '#mcp/iconic/handler')

    expect(code).toContain('icons: [{"src":"https://example.com/icon.png","mimeType":"image/png"}]')
    expect(code).toContain('websiteUrl: "https://example.com"')

    await iconic.close()
  })

  it('refuses two servers on one route', () => {
    expect(() => mcp().setup(nitro)).toThrow(/Two MCP servers are mounted on \/mcp/)
  })

  it('mounts a route written without its leading slash', async () => {
    const relaxed = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [mcp({ route: 'side/mcp/' })],
    })

    expect(relaxed.options.handlers).toMatchObject([{ route: '/side/mcp' }])

    await relaxed.close()
  })

  it('rejects a route that names nothing', () => {
    expect(() => mcp({ route: ' ' })).toThrow(/`route` cannot be empty/)
  })
})

describe('an empty definitions directory', () => {
  it('still generates the three arrays', async () => {
    const nitro = await createNitro({
      rootDir: fixtureDir,
      dev: false,
      preset: 'standard',
      modules: [mcp({ route: '/empty', dir: 'server/nothing-here' })],
    })

    await expect(render(nitro, '#mcp/empty/registry')).resolves.toMatchInlineSnapshot(`
      "// Generated by nitro-mcp-toolkit. Edit the files it lists instead.

      export const tools = []

      export const resources = []

      export const prompts = []
      "
    `)

    await nitro.close()
  })
})

// A file already in the registry reaches the bundler through its import; a file
// nobody imports yet needs the registry generated again first.
describe('watching for definitions in development', () => {
  let root: string
  let nitro: Nitro
  let reloads: number

  beforeAll(async () => {
    root = await mkdtemp(join(tmpdir(), 'nitro-mcp-watch-'))
    await mkdir(join(root, 'server/mcp/tools'), { recursive: true })

    nitro = await createNitro({ rootDir: root, dev: true, preset: 'nitro-dev', modules: [mcp()] })
    reloads = 0
    nitro.hooks.hook('rollup:reload', () => {
      reloads += 1
    })
  })

  afterAll(async () => {
    await nitro.close()
    await rm(root, { recursive: true, force: true })
  })

  it('rebuilds when a definition file appears, and again when it goes', async () => {
    const file = join(root, 'server/mcp/tools/late.ts')

    await writeFile(file, 'export default {}\n')
    await vi.waitFor(() => expect(reloads).toBeGreaterThan(0), { timeout: 10_000 })

    const afterAdd = reloads

    await rm(file)
    await vi.waitFor(() => expect(reloads).toBeGreaterThan(afterAdd), { timeout: 10_000 })
  })

  it('sees a definitions directory that did not exist yet', async () => {
    const late = await mkdtemp(join(tmpdir(), 'nitro-mcp-late-'))
    const lateNitro = await createNitro({
      rootDir: late,
      dev: true,
      preset: 'nitro-dev',
      modules: [mcp()],
    })
    let lateReloads = 0
    lateNitro.hooks.hook('rollup:reload', () => {
      lateReloads += 1
    })

    await mkdir(join(late, 'server/mcp/tools'), { recursive: true })
    await writeFile(join(late, 'server/mcp/tools/first.ts'), 'export default {}\n')
    await vi.waitFor(() => expect(lateReloads).toBeGreaterThan(0), { timeout: 10_000 })

    await lateNitro.close()
    await rm(late, { recursive: true, force: true })
  })

  it('ignores files that cannot hold a definition', async () => {
    const before = reloads

    await writeFile(join(root, 'server/mcp/notes.md'), 'not a definition\n')
    await writeFile(join(root, 'server/mcp/tools/notes.md'), 'not a definition\n')

    await new Promise((resolve) => setTimeout(resolve, 300))

    expect(reloads).toBe(before)
  })
})
