import { defineCachedFunction } from 'nitropack/runtime'
import ms from 'ms'

/**
 * Cache duration strings supported by the `ms` package
 */
export type MsCacheDuration
  = '1s' | '5s' | '10s' | '15s' | '30s' | '45s' // seconds
    | '1m' | '2m' | '5m' | '10m' | '15m' | '30m' | '45m' // minutes
    | '1h' | '2h' | '3h' | '4h' | '6h' | '8h' | '12h' | '24h' // hours
    | '1d' | '2d' | '3d' | '7d' | '14d' | '30d' // days
    | '1w' | '2w' | '4w' // weeks
    | '1 second' | '1 minute' | '1 hour' | '1 day' | '1 week'
    | '2 seconds' | '5 seconds' | '10 seconds' | '30 seconds'
    | '2 minutes' | '5 minutes' | '10 minutes' | '15 minutes' | '30 minutes'
    | '2 hours' | '3 hours' | '6 hours' | '12 hours' | '24 hours'
    | '2 days' | '3 days' | '7 days' | '14 days' | '30 days'
    | '2 weeks' | '4 weeks'
    | (string & Record<never, never>)

/**
 * Base cache options using Nitro's caching system
 * @see https://nitro.build/guide/cache#options
 */
export interface McpCacheOptions<Args = unknown> {
  /** Cache duration as string (e.g. '1h') or seconds (required) */
  maxAge: MsCacheDuration | number
  /** Duration for stale-while-revalidate */
  staleMaxAge?: number
  /** Cache name (auto-generated by default) */
  name?: string
  /** Function to generate cache key */
  getKey?: (args: Args) => string
  /** Cache group (default: 'mcp') */
  group?: string
  /** Enable stale-while-revalidate behavior */
  swr?: boolean
}

/**
 * Cache configuration: string duration, milliseconds, or full options
 * @see https://nitro.build/guide/cache#options
 */
export type McpCache<Args = unknown> = MsCacheDuration | number | McpCacheOptions<Args>

/**
 * Parse cache duration to seconds
 */
export function parseCacheDuration(duration: MsCacheDuration | number): number {
  if (typeof duration === 'number') {
    return duration
  }
  const parsed = ms(duration as Parameters<typeof ms>[0])
  if (parsed === undefined) {
    throw new Error(`Invalid cache duration: ${duration}`)
  }
  // Convert milliseconds to seconds for Nitro
  return Math.ceil(parsed / 1000)
}

/**
 * Create cache options from McpCache config
 */
export function createCacheOptions<Args>(
  cache: McpCache<Args>,
  name: string,
  defaultGetKey?: (args: Args) => string,
): Record<string, unknown> {
  if (typeof cache === 'object') {
    return {
      getKey: defaultGetKey,
      ...cache,
      maxAge: parseCacheDuration(cache.maxAge),
      name: cache.name ?? name,
      group: cache.group ?? 'mcp',
    }
  }

  return {
    maxAge: parseCacheDuration(cache),
    name,
    group: 'mcp',
    getKey: defaultGetKey,
  }
}

/**
 * Wrap a function with caching
 */
export function wrapWithCache<T extends (...args: unknown[]) => unknown>(
  fn: T,
  cacheOptions: Record<string, unknown>,
): T {
  return defineCachedFunction(
    fn,
    cacheOptions as Parameters<typeof defineCachedFunction>[1],
  ) as T
}
